---  
- name: synchronize source from local directory to remote directories
  synchronize:
    src: "{{ hydra_home }}"
    dest: "{{ hydra_home | dirname }}"

- name: compile resource monitor
  shell: make
  args:
    chdir: "{{ hydra_home }}/resource_monitor"